assembly_info:
  patch: false

build_script:
  - ps: ./build.ps1 -Target Build

artifacts:
  - path: '**\*.nupkg'

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/johnduhart-nuget-ci/api/v2/package
    symbol_server: https://www.myget.org/F/johnduhart-nuget-ci/symbols/api/v2/package
    api_key:
      secure: 3a5c7wSEJSm+SEGYU07ytloSKrgc+rZ1VavXlzDk7X6BgB5JLBps/STsBr2/8X8b
    on:
      branch: develop
  - provider: NuGet
    api_key:
      secure: HrYWG6EZvrSHWhteUWSISorcCs6+RMV4CruxySqe2d74GxQLI/hzBeO8qo5jhkcv
    on:
      branch: master